version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: always
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  inventory-app:
    build: .
    container_name: inventory-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ["java", "-jar", "app.jar"]

volumes:
  mysql_data:
